### ISSUE TITLE
Make it possible to use multiple filters

### ISSUE THREAD

**Issue by hamoid** [SableRaf/Filters4Processing#1]
Currently all shader files share the same name, so adding a second .glsl file to a project would overwrite the first one. Maybe instead of

```
myFilter = loadShader( "shader.glsl" );
```

we could use

```
bicubicFilter = loadShader( "bicubic.glsl" );
```

? That would allow using multiple filters on one sketch:

```
filter( bicubicFilter );
filter( ditheringFilter );
```

**Comment by SableRaf** [comment]
Fixed. Thanks Abe :)

**Comment by hamoid** [comment]
You rocks :+1: 

ps. readme.md too? :)

**Comment by SableRaf** [comment]
If you're talking about the code example, I think it can remain generic.
